repos:
  - repo: local
    hooks:
      - id: clean
        name: Clean generated artifacts
        entry: make clean
        language: system
        stages: [pre-commit]
        always_run: true
        pass_filenames: false
      - id: check-golden
        name: Check generated image matches golden
        entry: scripts/check_golden.sh
        language: script
        stages: [pre-commit]
        always_run: true
      - id: pytest
        name: Run pytest
        entry: uv run pytest --ignore=tests/test_ui_app.py
        language: system
        stages: [pre-commit]
        pass_filenames: false
        always_run: true
      #   This brings pain to keep clean. e.g. docs/released/html/searchindex.js has diffs upoon regeneration
      # - id: docs-html
      #   name: Build and verify HTML docs
      #   entry: bash -lc "make release-docs && git diff --exit-code docs/released/html"
      #   language: system
      #   stages: [pre-commit]
      #   pass_filenames: false
      #   always_run: true
